[package]
name = "bombastic-event-bus"
version = "0.1.0"
edition = "2021"

[dependencies]
rdkafka = { version = "0.25", features = ["cmake-build"], optional = true }
anyhow = "1"

[features]
default = ["kafka"]
kafka = ["rdkafka"]
