[package]
name = "bombastic-indexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
bombastic-index = { path = "../index" }
bombastic-storage = { path = "../storage" }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
