apiVersion: apps/v1
kind: Deployment
metadata:
  name: bombastic-api
  labels:
    app.kubernetes.io/name: bombastic-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: bombastic
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: bombastic-api
      app.kubernetes.io/component: api
      app.kubernetes.io/part-of: bombastic
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bombastic-api
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: bombastic
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - image: ghcr.io/xkcd-2347/bombastic:latest
          imagePullPolicy: Always
          name: service
          command: ["/bombastic"]
          args: ["api", "-p", "8080", "--index", "/data/index.sqlite"]
          volumeMounts:
            - name: data
              mountPath: /data
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
