[package]
name = "bombastic-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-s3 = "0.33"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
