name: nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # every night

permissions:
  contents: write # for creating a release

jobs:
  tag:
    runs-on: ubuntu-22.04
    needs: args
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.NIGHTLY_TOKEN }}

      - name: Clean old tags
        run: |
          ./.github/prune-nightly.sh

      - id: getflags
        run: |
          curl -sSLf https://github.com/TomWright/dasel/releases/download/v2.1.2/dasel_linux_amd64 -o dasel && chmod +x dasel
          echo "version=$(./dasel -f trust/Cargo.toml -r toml -s package.version)" >> "$GITHUB_OUTPUT"
          echo "commit=$(echo -n $GITHUB_SHA | head -c 8)" >> "$GITHUB_OUTPUT"

      - name: Tag it
        run: |
          git config --global user.email "ci@trustification.io"
          git config --global user.name "Trustification CI"
          git tag v${{ steps.getflags.outputs.version }}-nightly.${{ steps.getflags.outputs.commit }} -m 'Nightly release'
          git push --follow-tags
